#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Monogatari 腳本生成器"""

import json
from typing import List, Dict, Optional


class ScriptGenerator:
    """Monogatari 腳本生成器"""
    
    def __init__(self, config: dict = None):
        self.config = config or {}
    
    def generate_script(self, passages: List[Dict], 
                       characters: List[Dict],
                       scenes: List[Dict]) -> str:
        """
        生成 Monogatari script.js 內容
        
        Args:
            passages: 段落列表（processed.json 格式）
            characters: 角色列表
            scenes: 場景列表
        
        Returns:
            JavaScript 程式碼
        """
        script_dict = {}
        
        for passage in passages:
            name = passage.get('name', 'Unnamed')
            lines = self._convert_passage(passage, characters)
            script_dict[name] = lines
        
        # 確保有 Start
        if 'Start' not in script_dict:
            if script_dict:
                # 使用第一個段落作為 Start
                first_key = list(script_dict.keys())[0]
                script_dict['Start'] = [f"jump {first_key}"]
            else:
                script_dict['Start'] = ['"歡迎來到遊戲！"', 'end']
        
        # 生成 JavaScript
        js_lines = [
            "'use strict';",
            "/* global monogatari */",
            "",
            "// Game Script",
            "// Generated by Visual Novel Toolkit",
            "",
            f"monogatari.script({json.dumps(script_dict, ensure_ascii=False, indent=4)});",
        ]
        
        return '\n'.join(js_lines)
    
    def _convert_passage(self, passage: Dict, characters: List[Dict]) -> List:
        """轉換段落為 Monogatari 格式"""
        lines = []
        scene_id = passage.get('scene_id')
        shown_character = None
        
        # 場景切換
        if scene_id:
            lines.append(f"show scene {scene_id} with fadeIn")
        
        # 處理每一行
        for line in passage.get('lines', []):
            line_type = line.get('type', 'narration')
            
            if line_type == 'narration':
                # 旁白前隱藏角色
                if shown_character:
                    lines.append(f"hide character {shown_character}")
                    shown_character = None
                
                text = line.get('text', '')
                if text:
                    lines.append(text)
            
            elif line_type == 'dialogue':
                char_id = line.get('character', '')
                expression = line.get('expression', 'normal')
                text = line.get('text', '')
                
                if char_id and text:
                    # 切換角色
                    if shown_character != char_id:
                        if shown_character:
                            lines.append(f"hide character {shown_character}")
                        lines.append(f"show character {char_id} {expression} at center with fadeIn")
                        shown_character = char_id
                    elif expression != 'normal':
                        # 同一角色換表情
                        lines.append(f"show character {char_id} {expression} at center")
                    
                    lines.append(f"{char_id} {text}")
            
            elif line_type == 'action':
                action = line.get('action', '')
                if action == 'hide_character':
                    char = line.get('character', '')
                    if char:
                        lines.append(f"hide character {char}")
                        if shown_character == char:
                            shown_character = None
                elif action == 'show_character':
                    char = line.get('character', '')
                    expr = line.get('expression', 'normal')
                    if char:
                        lines.append(f"show character {char} {expr} at center with fadeIn")
                        shown_character = char
                elif action == 'change_scene':
                    new_scene = line.get('scene_id', '')
                    if new_scene:
                        lines.append(f"show scene {new_scene} with fadeIn")
        
        # 處理選項
        choices = passage.get('choices', [])
        if choices:
            # 隱藏角色
            if shown_character:
                lines.append(f"hide character {shown_character}")
            
            choice_obj = {'Choice': {}}
            for i, choice in enumerate(choices):
                text = choice.get('text', f'選項 {i+1}')
                target = choice.get('target', 'Start')
                choice_obj['Choice'][f'Option{i+1}'] = {
                    'Text': text,
                    'Do': f'jump {target}'
                }
            lines.append(choice_obj)
        
        return lines
    
    def generate_characters_js(self, characters: List[Dict]) -> str:
        """生成 characters.js"""
        char_dict = {}
        
        for char in characters:
            char_id = char.get('id', 'unknown')
            expressions = char.get('expressions', 
                                   char.get('expressions_needed', ['normal']))
            
            char_dict[char_id] = {
                'name': char.get('name', char_id),
                'color': char.get('color', self._get_color(char_id)),
                'directory': char_id,
                'sprites': {expr: f"{expr}.png" for expr in expressions}
            }
        
        js = [
            "'use strict';",
            "/* global monogatari */",
            "",
            "// Character Definitions",
            f"monogatari.characters({json.dumps(char_dict, ensure_ascii=False, indent=2)});",
        ]
        
        return '\n'.join(js)
    
    def generate_scenes_js(self, scenes: List[Dict]) -> str:
        """生成 scenes.js"""
        scene_dict = {}
        
        for scene in scenes:
            scene_id = scene.get('id', 'unknown')
            scene_dict[scene_id] = f"{scene_id}.jpg"
        
        js = [
            "'use strict';",
            "/* global monogatari */",
            "",
            "// Scene Definitions",
            f"monogatari.assets('scenes', {json.dumps(scene_dict, ensure_ascii=False, indent=2)});",
        ]
        
        return '\n'.join(js)
    
    def generate_options_js(self, title: str) -> str:
        """生成 options.js"""
        return f'''\'use strict\';
/* global monogatari */

// Game Settings
monogatari.settings({{
    "Name": "{title}",
    "Version": "1.0.0",
    "Preload": true,
    "AutoSave": 10000,
    "AutoSaveLabel": "自動存檔",
    "SaveLabel": "存檔",
    "SaveFormat": "第 X 天",
    "ShowSlotMeta": true
}});

// Assets path configuration
monogatari.settings({{
    "AssetsPath": {{
        "root": "assets",
        "characters": "characters",
        "scenes": "scenes",
        "music": "music",
        "sounds": "sounds",
        "voices": "voices",
        "images": "images",
        "gallery": "gallery"
    }}
}});

// Language and preferences
monogatari.preferences({{
    "Language": "繁體中文",
    "TextSpeed": 30,
    "AutoPlaySpeed": 5
}});
'''
    
    def generate_main_js(self) -> str:
        """生成 main.js"""
        return '''\'use strict\';
/* global monogatari */

// Initialize Monogatari
monogatari.init('#monogatari').then(function() {
    console.log('Monogatari initialized successfully');
});
'''
    
    def generate_storage_js(self) -> str:
        """生成 storage.js"""
        return '''\'use strict\';
/* global monogatari */

// Storage settings
monogatari.storage({
    player: {
        name: ""
    }
});
'''
    
    def _get_color(self, char_id: str) -> str:
        """根據角色 ID 生成顏色"""
        colors = [
            '#ff6b6b', '#4ecdc4', '#45b7d1', '#96ceb4',
            '#ffeaa7', '#dda0dd', '#f8b739', '#a8e6cf',
            '#ff9ff3', '#54a0ff', '#5f27cd', '#00d2d3'
        ]
        hash_val = sum(ord(c) for c in char_id)
        return colors[hash_val % len(colors)]
